// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhRVL3TO7gqMZEaX05Ga1-BOf4OITXc58',
    appId: '1:896347798482:web:14f0851a690e5709aae60b',
    messagingSenderId: '896347798482',
    projectId: 'app-gestao-salao',
    authDomain: 'app-gestao-salao.firebaseapp.com',
    storageBucket: 'app-gestao-salao.firebasestorage.app',
    measurementId: 'G-YT6TPV8RJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fq_ezXgeX16xmAyanxN9GWupWGtsJR4',
    appId: '1:896347798482:android:b8cb042964652c18aae60b',
    messagingSenderId: '896347798482',
    projectId: 'app-gestao-salao',
    storageBucket: 'app-gestao-salao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmx-zGM2-UuzkoSt4Y4tEQd3OUpGSB6Mc',
    appId: '1:896347798482:ios:f11ea7b4bb802f24aae60b',
    messagingSenderId: '896347798482',
    projectId: 'app-gestao-salao',
    storageBucket: 'app-gestao-salao.firebasestorage.app',
    iosBundleId: 'com.example.gestaoSalao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmx-zGM2-UuzkoSt4Y4tEQd3OUpGSB6Mc',
    appId: '1:896347798482:ios:f11ea7b4bb802f24aae60b',
    messagingSenderId: '896347798482',
    projectId: 'app-gestao-salao',
    storageBucket: 'app-gestao-salao.firebasestorage.app',
    iosBundleId: 'com.example.gestaoSalao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhRVL3TO7gqMZEaX05Ga1-BOf4OITXc58',
    appId: '1:896347798482:web:8c4016bf34ede41faae60b',
    messagingSenderId: '896347798482',
    projectId: 'app-gestao-salao',
    authDomain: 'app-gestao-salao.firebaseapp.com',
    storageBucket: 'app-gestao-salao.firebasestorage.app',
    measurementId: 'G-CX29S88B87',
  );
}
